=== CloudletLabs/clh-web-api/raml/schemas/newss.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "array",
  "required": true,
  "items": {
    "type": "object",
    "required": true,
    "properties": {
      "slug": {
        "type": "string",
        "required": true
      },
      "creator": {
        "type": "object",
        "required": true,
        "properties": {
          "name": {
            "type": "string",
            "required": true
          }
        }
      },
      "subject": {
        "type": "string",
        "required": true
      },
      "text": {
        "type": "string",
        "required": true
      },
      "createDate": {
        "type": "string",
        "required": true
      }
    }
  }
}

=== CloudletLabs/clh-web-api/raml/bodies/responses/newss.json
[
  {
    "slug": "second-news",
    "creator": {
      "name": "Admin"
    },
    "subject": "Second News",
    "text": "This is a second test news!",
    "createDate": "2016-06-19T15:59:25.054Z"
  },
  {
    "slug": "hello-world",
    "creator": {
      "name": "Admin"
    },
    "subject": "Hello World!",
    "text": "**This** is a **first** test news! `Welcome!`",
    "createDate": "2016-06-18T15:59:25.390Z"
  }
]
